
version: '3.8'

services:
  wallet-factory:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-/api}
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./logs:/var/log/nginx
      - wallet-data:/data
    environment:
      - NODE_ENV=production

volumes:
  wallet-data:
    driver: local
