
version: '3.8'

services:
  wallet-factory:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-/api}
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./logs:/var/log/nginx
      - wallet-data:/data
    environment:
      - NODE_ENV=production
      # Pass server information to the application
      - SERVER_CPU_CORES=${SERVER_CPU_CORES:-16}
      - SERVER_MEMORY_MB=${SERVER_MEMORY_MB:-32768}

volumes:
  wallet-data:
    driver: local
